### PR TITLE
format_phyloseq

### PR DESCRIPTION
**Pull request by microsud**
The biom file created using greengenes and SILVA database have certain formatting features that need to be formatted for clarity and better downstream analysis with phyloseq and microbiome packages in R.

### CODE REVIEW

**Comment by microsud** [comment]
#' Saving otu,taxonomy and meta data as *.csv file for manual inspection
#'
#' @param type "OTU" or "TAXA" or METADATA
#' @return
#' @examples
#' save.tables(p0, "OTU")
#' save.tables(p0, "TAXA")
#' save.tables(p0, "Metadata")
#' microbiomeutilities
#'
#'
save.tables <- function(pseq_object, type){
  if (type == "OTU"){
    x <- as.data.frame(pseq_object@otu_table);
    write.csv(x, file = "otu_table.csv", fileEncoding = "UTF-16LE");
	paste0("Your OTU file is saved here:- ", getwd())
    } else if (type == "TAXA"){
  x <- as.data.frame(pseq_object@tax_table);
  write.csv(x, file ="taxa_table.csv", fileEncoding = "UTF-16LE");
  paste0("Your Taxonomy file is saved here:- ", getwd())
} else if (type == "METADATA"){
  x <- as.data.frame(pseq_object@sam_data);
  write.csv(x, file = "meta_table.csv", fileEncoding = "UTF-16LE");
  paste0("Your metadata file is saved here:- ", getwd())
  }
}

This command can be useful for users who would like to manually inspect the files since there can be issues in the biom file.

**Comment by antagomir** [comment]
Thanks! All checks pass and the pull request process seems to proceed very smoothly. 

Before merging, I have some kind requests:

- Can you polish the roxygen documentation? This is essential for later Bioc submission. The exported functions should have also fields @title, @description, @return and other fields. For examples, see the existing microbiome functions and modify from there. I will then check in more detail on the second round if they fulfil the requirements. Please also add the field @export on those functions that should be made available to users.

-  None of the examples should write on disk . Therefore, can you add \dontrun{} around the examples that would write on disk. Again, you can find examples in other functions.

- Do we have any (small) example data set that we could add in the package and use in the examples?  This can be omitted but it would make the examples more concrete and also help to automatically check function performance

- Consider polishing the code in the R functions either with the formatR package or using a similar style as in other functions (I leave it to you but small effort to harmonize the style could benefit both of us in the longer term)

- Could we have a brief tutorial page - ie. new Rmd file in the vignettes folder. Some examples should be added in the vignette for each exported function. This helps to keep track on all functionalities in the package and provides also automated testing as the vignettes are regularly updated when something changes.

**Comment by microsud** [comment]
Hi Leo- Thanks! I was wondering if it was ok that I create a single vignette/rmd file for adapting the high throughput seq data? Also not sure if I can use the NG-Tax data at this point since the publication is still under process.

**Comment by antagomir** [comment]
Yes, one tutorial Rmd would be good for now. It is easy to reorganize later if that turns out to be necessary. If the NG-Tax data can't be used then that can't be included in any examples for now. Or you could consider making some small toy data set based on that (shuffling number and IDs so as to remove all real information from the data - this would be still valid for an example and can be later replaced by real data).

**Comment by antagomir** [comment]
By the way if you can easily redirect this pull request to the devel branch please do. If there are problems, I can handle this with master now but at least for the later PRs make them to devel branch.

**Comment by microsud** [comment]
Hi Leo- I have tried to incorporate the changes suggested by you. Could not find a function in qiimer to taxsize R packages that handle phyloseq object similar to format_phyloseq function. This code is a slight modification of the code from Ampvis package, which takes an ampvis formatted object as input and returns a phyloseq object. I think the adaptation to phyloseq as input will be more convenient for users. Your suggestions are welcome.  I am working on making the example dataset.

**Comment by antagomir** [comment]
Thanks, see my latest comments. Some change still needed before I can accept the merge. I hope this is ok. The function looks very good already & we are almost there.

**Comment by microsud** [comment]
I have checked the file and reformatted the scripts along with the devtools check and build. In addition, I have the example data set from the Dynamics of gut microbiota in IBD study downloaded from qiita. How do I upload those files? Should I just email you the files?

**Comment by antagomir** [comment]
If the example file is from QIITA then I think there is an R command to download the data directly from there. Is it necessary to have the data in this R package ? Instead, you could just show the QIITA download command in the examples ?

**Comment by antagomir** [comment]
The format_phyloseq function should be located in folder R/ (and not the root folder where it is now). Moreover, the function should be named "format_phyloseq.R" (not "format_phyloseq" without ending). Can you do and make the PR ?

**Pull request merged**
