### PR TITLE
Update data.R

### PR DESCRIPTION
**Pull request by microsud**
Author name changed

### CODE REVIEW

**Comment by microsud** [comment]
@antagomir Cannot upload the DynamicsIBD.rda file. I think I need push access? Please suggest how to proceed.

**Comment by antagomir** [comment]
Ok, does it work now ?

**Comment by microsud** [comment]
@antagomir Yes. Data now uploaded. Few more things:
The format_phyloseq.R is not in the R folder.
Missing plot_taxa_frequency and save.tables functions.
Also, I want to test the entire package for DynamicsIBD dataset.

**Comment by antagomir** [comment]
Can you move format_phyloseq in the R folder ?

Why the plot plot_taxa_frequency and save.tables functions are missing ? Can you add or is there a problem ?

If you want to test the package for that data set, just add all the necessary elements in your local fork and load the package with devtools::load_all() then you can test it all before making PR.

**Pull request merged**
