### PR TITLE
save_tables.R

### PR DESCRIPTION
**Pull request by microsud**
Wrapper to save files with taxonomic, OTU or metadata information from Phyloseq object.

### CODE REVIEW

**Comment by antagomir** [comment]
Can you make this pull request to devel branch instead of master.

**Comment by microsud** [comment]
Thanks will do these changes ASAP

**Comment by antagomir** [comment]
Thank a lot & sorry to being picky but let's do it properly at one go. My remaining suggestions before merge:

- For consistency, use quotes also around the term "METADATA" in the @parameter field

- Return the full file path ie for instance: message("Writing METADATA in the file ", paste(getwd(), "meta_table.csv", sep = "/")). 

- To be safe it would be helpful to define the function name separately as `f <- paste(getwd(), "meta_table.csv", sep = "/")` and then call `message("Writing METADATA in the file ", f)` as well as `write.csv(.. file = f.. )` This way you can make sure the message file and output file really are the same.

 - The final line: "paste0("File saved in folder ", getwd())" is now unnecessary if you already give messages within each elseif statement. 

- In this function manpage, use one of our own data sets in this example (for instance dietswap) and remove the format_phyloseq - that is independent and just complicates the example. In the tutorial you can then show how to use this in your particular case with external data sets and combine formatting etc.

**Comment by antagomir** [comment]
R CMD check gives:

save_tables: no visible global function definition for ‘write.csv’
Undefined global functions or variables:
  write.csv
Consider adding
  importFrom("utils", "write.csv")

-> Can you fix ? In practice, add a new "@importFrom utils write.csv" in the firstlib.R file. If you have linux or mac, please run R CMD build and R CMD check (for examples, see inst/extras/build.sh) to make sure there are no warnings or errors.

**Pull request merged**
